# -*- coding: utf-8 -*-
from wx.lib.embeddedimage import PyEmbeddedImage

# Colors
FRAME_BGCOLOR = "#FEFEFE"
PANEL_BGCOLOR = FRAME_BGCOLOR

FIGURE_BGCOLOR = "#DADADA"
AXES_BGCOLOR = "#F0F0F0"

CONTROL_BGCOLOR = FRAME_BGCOLOR

# Icons
fig_icon = PyEmbeddedImage(
    "iVBORw0KGgoAAAANSUhEUgAAAA4AAAAKCAYAAACE2W/HAAAABHNCSVQICAgIfAhkiAAAAAlw"
    "SFlzAAAN1wAADdcBQiibeAAAABl0RVh0U29mdHdhcmUAd3d3Lmlua3NjYXBlLm9yZ5vuPBoA"
    "AADySURBVCiRndC/L0NxFAXwz/u2JSQGMdnEpGmikTBphFViZDexMfoTTEaL0e/NwiJEE2kM"
    "DfXS1D+BiUW0z9BWXuRNznjuOffcc/kHYh7yf4gp7OGzwGaRtwzTJN5Dn2gxjsMO27j4Zjcr"
    "LWIJ1V/imbOYZUiIYuI6wxmJJ03mAjQoRYxOc9XbmuBmgMW0KSFgpsVjgMBWp9stjWpCJU00"
    "WUBtjXaoMYT5Mtdp0Rf3usI01gNHEEZYibiM6KQVs7xG5F4YgycmEool7iAkrLY5zfpgwvkX"
    "G3UKOQ4Sdnr9BXyUaWQZ8+xHVAa7Zx+Xue3PfgAthj9o8IJiMQAAAABJRU5ErkJggg==")
